### ISSUE TITLE
backgroundColor

### ISSUE THREAD

**Issue by byteManishPatidar** [Dn-a/flutter_inner_drawer#87]
flutter_inner_drawer-1.0.0+1/lib/inner_drawer.dart:585:38: Error: The getter 'backgroundColor' isn't defined for the class 'ThemeData'.

**Comment by byteManishPatidar** [comment]
Got this error when run project

**Comment by Kav47** [comment]
Until this [change is merged](https://github.com/Dn-a/flutter_inner_drawer/pull/84), you may use the following workaround in your **pubspec.yaml** file:

```yaml 
flutter_inner_drawer: 
    git:
      url: https://github.com/amerchDev/flutter_inner_drawer.git
      ref: flutter-3.22.2-null-safety-and-deprecated-theme-background-fix
```
